version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/railway
      - SPRING_DATASOURCE_USERNAME=${MYSQLUSER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLPASSWORD}
      - APP_JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}
    ports:
      - "3306:3306"
